name: CompareGenerateJsonHash
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARTS_FUNC: ${{ startWith('Hello', 'He') }}
          ENDS_FUNC: ${{ endwWith('Hello', 'lo')}}
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{0}, {1}.','Hi', 'world') }}
          JOIN_FUNC: ${{ join(github.event.*.html_url,', ')}}
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${CONTEXT}"
        env:
          CONTEXT: ${{ toJSON(github)}}
  hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${HASH}"
        env:
          HASH: ${{ hashFiles('.github.workflows/*.yml') }}
